# Generated by Django 5.1.4 on 2024-12-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEmployee', '0003_rename_categoryes_adminemployeecredentials_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminemployeecredentials',
            name='categories',
        ),
    ]
