# Generated by Django 5.1.4 on 2024-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEmployee', '0004_remove_adminemployeecredentials_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemployeecredentials',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='adminemployee', to='AdminEmployee.categories'),
        ),
    ]
