# Generated by Django 5.1.4 on 2024-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEmployee', '0005_adminemployeecredentials_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categoryName',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
