# Generated by Django 5.1.4 on 2024-12-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEmployee', '0006_alter_categories_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='subcategoryName',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
