# Generated by Django 5.1.4 on 2024-12-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEmployee', '0007_alter_subcategories_subcategoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemployeecredentials',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
