# Generated by Django 5.1.4 on 2024-12-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminEmployee', '0008_adminemployeecredentials_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemployeecredentials',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='adminemployee', to='AdminEmployee.categories'),
        ),
    ]
